name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-to-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: --archive --verbose --compress --human-readable --progress --delete --delete-excluded
          path: .
          remote_path: /home/jj125967/domains/riceofcapitalism.com/public_html/
          remote_host: ${{secrets.SSH_HOST}}
          remote_user: ${{secrets.SSH_USER}}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: ${{ secrets.SSH_PORT }}
